# Generated by Django 5.0.2 on 2024-02-21 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], max_length=1)),
                ('id_card_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Id Card Number must be integer type', regex='^[0-9]*$')])),
                ('address', models.CharField(max_length=200)),
                ('is_married', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
