# Generated by Django 5.0.2 on 2024-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], default=('N', 'None'), max_length=1),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='id_card_number',
            field=models.CharField(max_length=10),
        ),
    ]
