# Generated by Django 5.0.2 on 2024-02-21 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_datamodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='id_card_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Id Card Number must be integer type', regex='^[0-9]*$')]),
        ),
    ]
